n_estimators: 100
max_depth: 10
min_samples_split: 2
min_samples_leaf: 1
model_path: 'model.joblib'
X_train_path: 'X_train.csv'
y_train_path: 'y_train.csv'
X_test_path: 'X_test.csv'
predicted_path: "predicted.csv"