preparation:
  y_column: 'Price'
  test_size: 0.3
  random_state: 42
model_parameters:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
paths:
  data: 'data/data.csv'
  X_test: 'data/X_test.csv'
  y_test: 'data/y_test.csv'
  model: 'model.joblib'